baseURL = 'https://jchirayil.github.io/'
languageCode = 'en-us'
title = 'Indix-Docs'
copyright = "(c) 2025 - Indix Docs. All rights reserved."
theme = "PaperMod"
[caches]
    [caches.images]
        dir = ':cacheDir/images'
[menus]
    [[menus.main]]
        name = "Home"
        pageRef = "/"
        weight = 10
    [[menus.main]]
        name = "Suggest"
        pageRef = "/suggest"
        weight = 20
    [[menus.main]]
        name = "About"
        pageRef = "/about"
        weight = 20